import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        elements: {
          formButtonPrimary: "bg-primary hover:bg-primary/90",
          card: "bg-background border-border",
          headerTitle: "text-foreground",
          headerSubtitle: "text-muted-foreground",
          socialButtonsBlockButton:
            "bg-background border-border text-foreground hover:bg-muted",
          formFieldLabel: "text-foreground",
          formFieldInput: "bg-background border-input text-foreground",
          footerActionLink: "text-primary hover:text-primary/90",
          identityPreview: "bg-background border-border",
          userButtonPopoverCard: "bg-background border-border",
          userButtonPopoverActionButton: "text-foreground hover:bg-muted",
          userButtonPopoverActionButtonIcon: "text-muted-foreground",
          userButtonPopoverFooter: "text-muted-foreground",
        },
      }}
    >
      <html lang="en">
        <body className="dark">
          <>
            {children}
            <Toaster />
          </>
        </body>
      </html>
    </ClerkProvider>
  );
}
